eventsWeb/events/Controllers/CartController.cs
using events.Identity;
using events.Models;
using eventsWeb.business.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace events.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<User> _userManager;
        public CartController(ICartService cartService, UserManager<User> userManager)
        {
            _cartService = cartService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var model = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i=>new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.ProductId,
                    Name=i.Product.Name,
                    Price= (double)i.Product.Price,
                    ImgUrl = i.Product.ImgUrl,
                    Quantity=i.Quantity
                }).ToList()
            };

            return View(model);
        } 

        [HttpPost]
         public IActionResult AddToCart(int productId, int  quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.AddToCart(userId, productId, quantity);

            return RedirectToAction("Index");
        }     

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            var userId = _userManager.GetUserId(User);   
            _cartService.DeleteFromCart(userId,productId);
            return RedirectToAction("Index");
        }    
    }
}

eventsWeb/events/Controllers/EventsController.cs
using events.Models;
using eventsWeb.business.Abstract;
using eventsWeb.entity;
using Microsoft.AspNetCore.Mvc;

namespace events.Controllers
{
    public class EventsController:Controller
    {
        public IProductService _productService;

        public EventsController(IProductService productService)
        {
            this._productService=productService;
        }
 
        public IActionResult list(int? id, string q)
        {
            if(id!=null)
            {
                var productsByCtgId = new ProductListViewModel()
                {
                    Products=_productService.GetProductByCategoryId((int)id)
                };

               return View(productsByCtgId); 
            }
            else if(!string.IsNullOrEmpty(q))
            {
                var productBySearch= new ProductListViewModel()
                {
                    Products= _productService.GetProductsByQSearch(q)
                };
                return View(productBySearch);
            }
            else
            {
                var productListViewModel = new ProductListViewModel()
                {
                    Products=_productService.GetAll()
                };
                return View(productListViewModel);
            }
        }
        
        public IActionResult detail(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }

            Product product = _productService.GetProductDetails((int)id);
            //Detay sayfasına ürünün kategorilerini de yazdırdım.
            // Buyüzden GetById metodu yerine tabloları bağlayarak bu metodu kullandım
            
            if(product==null)
            {
                return NotFound();
            }

            return View(new ProductDetailModel{
                Product = product,
                Categories = product.ProductCategories.Select(i=>i.Category).ToList()
            });
        }        
    }
}

eventsWeb/events/ViewComponents/CategoriesViewComponent.cs
using eventsWeb.business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace events.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoriesViewComponent(ICategoryService categoryService)
        {
            this._categoryService  = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory=RouteData?.Values["id"];
            return View(_categoryService.GetAll());
        }        
    }
}

eventsWeb/events/Views/Events/Detail.cshtml
@model events.Models.ProductDetailModel
    
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("Categories")
        </div>  

        <div class="col-md-9">
            @* <div class="card mb-3"> *@
                <div class="card-body">
                    <div class="row no-gutters">
                        <div class="col-md-3" >
                            <img src="~/img/@Model.Product.ImgUrl" class="card-img" style="box-shadow: 3px 3px 5px  #888888;" >
                        </div>
                        <div class="col-md-9">

                            <h5 class="card-title">@Model.Product.Name</h5>

                            @foreach (var item in Model.Categories)
                            {
                                <a href="/events/list/@item.CategoryId" class="btn btn-link -0 mb-3"> @item.Name </a>
                            }
                            <p class="card-text">@Html.Raw(Model.Product.Description)</p>
                            <p class="card-text">@Model.Product.eventDate</p>
                            <p class="card-text">@Model.Product.Location</p>
                            @* <p class="card-text">
                                <small class="text-muted">3 Days Ago</small>
                            </p> *@
                            @* <i class="fa fa-turkish-lira">@Model.Product.Price</i>   *@
                            <div class="mb-3">
                                <h4 class="text-secondary mb-3">
                                    <i class="fa fa-turkish-lira">@Model.Product.Price</i>
                                </h4>
                                <form asp-controller="Cart" asp-action="AddToCart" method="POST" class="form-inline" >
                                    <input type="hidden" name="productId" value="@Model.Product.ProductId">
                                    <div class="input-group mb-3">
                                    <div class="row" style="margin-right: 20px;">
                                        <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width: 100px;">
                                     </div> 
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-secondary">
                                                <i class="fas fa-cart-plus"></i> Karta Ekle                               
                                            </button>
                                        </div>
                                    </div>     
                                </form>
                            </div>

 
                        </div>
                    </div>
                </div>

                <div class="col-md-5" >
                    <br>
                    <h5>Oturma Planı</h5><hr>
                    <img src="~/img/@Model.Product.sittingUrl" class="card-img" style="box-shadow: 0px 0px 1px  #888888;" >
                </div>
        
            @* </div> *@
        </div>  
    </div>

eventsWeb/events/Views/Events/List.cshtml
   @model events.Models.ProductListViewModel
    <div class="row">
        <div class="col-md-2">
            @await Component.InvokeAsync("Categories")
        </div>
         <div class="col-md-10">
            <div class="row">
                @foreach (var product in Model.Products)
                {
                    <div class="col-md-3">
                        @await Html.PartialAsync("~/Views/Shared/_productCard.cshtml", product)
                    </div>
                }
            </div>
         </div>
    </div>